name: bitcoin_ui_kit
description: The Bitcoin UI Kit for Flutter.
version: 1.0.3
homepage: https://github.com/bdgwallet/bitcoinuikit-flutter

environment:
  sdk: ">=2.18.5 <=3.0.5"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
