name: bitcoin_ui
description: The Bitcoin UI Kit for Flutter.
version: 1.0.4
homepage: https://github.com/bdgwallet/bitcoinui-flutter

environment:
  sdk: ">=2.18.5 <=3.0.5"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - icons/
